# Generated by Django 3.1.7 on 2021-03-25 02:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0004_auto_20210324_1737'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Editor',
        ),
        migrations.AlterField(
            model_name='article',
            name='article_image',
            field=models.ImageField(blank=True, upload_to='articles/'),
        ),
    ]
